import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val androidx_room: String = "2.2.5"

    const val com_android_support_test_runner: String = "1.0.2"

    const val com_android_tools_build_gradle: String = "4.1.1"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val kotlin_annotation_processing_gradle: String = "1.4.10" // available: "1.4.21"

    const val kotlin_android_extensions_runtime: String = "1.4.10" // available: "1.4.21"

    const val kotlin_android_extensions: String = "1.4.10" // available: "1.4.21"

    const val kotlin_gradle_plugin: String = "1.4.10" // available: "1.4.21"

    const val kotlin_stdlib_jdk7: String = "1.4.21"

    const val espresso_core: String = "3.0.2"

    const val lint_gradle: String = "27.1.1"

    const val appcompat: String = "1.2.0"

    const val aapt2: String = "4.1.1-6503028"

    const val junit: String = "4.13.1"

    /**
     * Current version: "6.7.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.7.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
